# Default values for webappchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

cert_issuer:
  email: "dacrook@microsoft.com"
  tls_secret_name: "ftaiot-prod"
  server: "https://acme-prod-v02.api.letsencrypt.org/directory"

web_app:
  fqdn: "ftaiot.eastus.cloudapp.azure.com"
  fqdntwo: "www.ftaiot.eastus.cloudapp.azure.com"
  image: "ftaiot.azurecr.io/ftaiot"
  containername: "ftaiotcontainer"
  env:
    DEVICE_DEPLOY_NAME: "iot_leaf_device"
    SECRET_KEY: "DEV_SECRETS"
names:
  deployment: "ftaiotdeployment"
  service: "ftaiotservice"
  ingress: "ftaiotingress"
  cert_issuer: "ftaiotcert_issuer"
  host: "ftaiot.eastus.cloudapp.azure.com"