apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.names.cert_issuer }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.cert_issuer.server }}
    # Email address used for ACME registration
    email: {{ .Values.cert_issuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.cert_issuer.tls_secret_name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx