kind: Deployment
apiVersion: v1
metadata:
  name: {{ .Values.names.deployment }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.names.deployment }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.deployment }}
    spec:
      containers:
      - name: {{ .Values.webapp.containername }}
        image: {{ .Values.web_app.image }}
        imagePullPolicy: Always
        env:
        - name: DEVICE_DEPLOY_NAME
          value: {{ .Values.web_app.env.DEVICE_DEPLOY_NAME }}