kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.names.service }}
spec:
  selector:
    app: {{ .Values.names.deployment }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP