FROM continuumio/miniconda3

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl -y
RUN apt-get install build-essential libssl-dev libffi-dev unixodbc-dev -y
RUN pip install --upgrade pip setuptools wheel
RUN apt-get install build-essential -y

RUN conda install psutil -y

######################################
#       START SECTION                #
#       INSTALL KUBECTL              #
######################################
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
RUN apt-get update
RUN apt-get install kubectl -y

######################################
#       START SECTION                #
#       INSTALL HELM                 #
######################################
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh

######################################
#       START SECTION                #
#       CREATE APP                   #
######################################
ADD requirements.txt /webapp/
RUN pip install -r /webapp/requirements.txt

EXPOSE 80

COPY . /webapp/

RUN mv /webapp/run.py /run.py

RUN chmod -x /run.py

# Ensure that Python outputs everything that's printed inside
# the application rather than buffering it.
ENV PYTHONUNBUFFERED 1

CMD ["python", "/run.py"]
#CMD ["gunicorn", "-b", "0.0.0.0:80", "-w", "4", "run:app"]