FROM continuumio/miniconda3

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install curl -y
RUN apt-get install build-essential libssl-dev libffi-dev unixodbc-dev -y
RUN pip install --upgrade pip setuptools wheel
RUN apt-get install build-essential -y

RUN conda install psutil -y

ADD requirements.txt /webapp/
RUN pip install -r /webapp/requirements.txt

EXPOSE 80

COPY . /webapp/

RUN mv /webapp/run.py /run.py

RUN chmod -x /run.py

# Ensure that Python outputs everything that's printed inside
# the application rather than buffering it.
ENV PYTHONUNBUFFERED 1

CMD ["python", "/run.py"]
#CMD ["gunicorn", "-b", "0.0.0.0:80", "-w", "4", "run:app"]